server:
  port: 30010
spring:
  application:
    name: issueMoaBatch
  config:
    import: optional:configserver:http://localhost:8888
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
logging:
  level:
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

endpoint:
  naver:
    news:
      rank: https://news.naver.com/main/ranking/popularDay.naver
  google:
    youtube:
      popular: https://www.googleapis.com/youtube/v3/videos

cron:
  expression:
    naverNewsRank: 0 0 * * * * # 매시 정각
    youtubePopular: 0 0 * * * * # 매시 정각