server:
  port: 17070
spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/issuemoa_batch
    username: admin
    password: ENC(C8W5kbP0b3KEGQTSAuvsvQ==)
  data:
    mongodb:
      host: localhost
      port: 27017
      database: issuemoa
logging:
  level:
    root: info

cron:
  expression:
    naverNewsRank: 0 0 */2 * * *

jasypt:
  key: ${jasyptKey}

endpoint:
  naver:
    news:
      rank: https://news.naver.com/main/ranking/popularDay.naver