server:
  port: 20010
spring:
  application:
    name: issueMoaBatch
  profiles:
    active: docker
  config:
    import: optional:configserver:http://issuemoa-config:8888
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
logging:
  level:
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://issuemoa-eureka:8761/eureka

endpoint:
  naver:
    news:
      rank: https://news.naver.com/main/ranking/popularDay.naver
  google:
    youtube:
      popular: https://www.googleapis.com/youtube/v3/videos

cron:
  expression:
    naverNewsRank: 0 0 * * * * # 매시 정각
    youtubePopular: 0 0 * * * * # 매시 정각