server:
  port: 17070
spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/issuemoa_batch
    username: admin
    password: ENC(C8W5kbP0b3KEGQTSAuvsvQ==)
  data:
    mongodb:
      host: localhost
      port: 27017
      database: issuemoa
logging:
  level:
    root: info

cron:
  expression:
    naverNewsRank: 0 0 */12 * * * # 12시간 마다
    youtubePopular: 0 0 * * 3 * # 매주 수요일 

jasypt:
  key: ${jasyptKey}

endpoint:
  naver:
    news:
      rank: https://news.naver.com/main/ranking/popularDay.naver
  google:
    youtube:
      popular: https://www.googleapis.com/youtube/v3/videos
api:
  key:
    google: ENC(exO2RqRPBk7bZ34Pm6GeGGG6LmFDtvUVw2WkB01AjjGxq0O39VffrdaLd5ubeTUV)